@startuml
class veryWeakP{
+ only numbers
+ less than 8 characters
}

class weakP{
+ only letters
+ less than 8 characters
}

class strongP{
+ letters and at least one number
+ at least 8 characters
}

class veryStrongP{
+ letters, numbers, and special characters
+ at least 8 characters
}


@enduml